</section>

<!-- Start of FOOTER INCLUDE file -->
<footer>

<!-- CONTACT US FORM -->
  <div class="contactform">
    <div class="row">
      <div class="column">
        <h2>Contact Us</h2>
      </div>
    </div>
    <div class="row">
      <div class="medium-6 column">
        <label>Name
          <input type="text" placeholder="Name" />
        </label>
        <label>E-mail
          <input type="text" placeholder="E-mail" />
        </label>
        <label>Phone
          <input type="text" placeholder="Phone" />
        </label>
        <label>Organization
          <input type="text" placeholder="Organization" />
        </label>
        <label>State/Province
          <input type="text" placeholder="State/Province" />
        </label>
      </div>
      <div class="medium-6 column">
        <label>Message
          <textarea style="min-height:267px" placeholder="Message"></textarea>
        </label>
        <p><a href="#" class="expand button">Submit</a>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="column">
        <div class="panel text-center">
          <h2>Don't feel like filling out a form? Call us!</h2>
          <h2>781.821.0000</h2>
        </div>
      </div>
    </div>

  </div>
<!-- END CONTACT US FORM -->


<!-- NEWSLETTER -->
  <div class="newsletter">
    <div class="row">
      <div class="column text-center">
        <h3 style="color:#3e4545;">Sign up for our Newsletter</h3>
        <div class="row collapse text-center">
          <div class="medium-3 column hide-for-small-only">
            <p>&nbsp;</p>
          </div>
          <div class="medium-4 small-10 columns">
            <input type="text" placeholder="Enter a valid e-mail address">
          </div>
          <div class="medium-2 small-2 columns">
            <a href="#" class="button postfix">Go</a>
          </div>
          <div class="medium-3 column hide-for-small-only">
            <p>&nbsp;</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- END NEWSLETTER -->

<!-- SITEMAP -->
  <div class="sitemap">
    <div class="row">
      <div class="medium-4 column">
        <h4><a href="solutions.php">EHR Solutions</a></h4>
        <ul>
          <li><a href="solutions-improveoutcomes.php">Improve Outcomes</a>
          </li>
          <li><a href="solutions-focuspatient.php">Focus on the Patient</a>
          </li>
          <li><a href="solutions-physicianadoption.php">Spark Physician Adoption</a>
          </li>
          <li><a href="solutions-READY.php">Be “READY” from the Start</a>
          </li>
          <li><a href="solutions-regulations.php">Meet Regulations</a>
          </li>
          <li><a href="solutions-data.php">Put Your Data to Work</a>
          </li>
          <li><a href="solutions-financialperformance.php">Drive Financial Performance</a>
          </li>
          <li><a href="solutions-share.php">Share Information</a>
          </li>
          <li>Raise the Bar
          </li>
          <li><a href="solutions-physician.php">Physicians</a>
          </li>
          <li><a href="solutions-nurse.php">Nurses & Patient Care</a>
          </li>
          <li><a href="solutions-emergency.php">Emergency Medicine</a>
          </li>
          <li><a href="solutions-clinical.php">Clinical Departments</a>
          </li>
          <li><a href="solutions-him.php">HIM</a>
          </li>
          <li><a href="solutions-executive.php">Executives</a>
          </li>
          <li><a href="solutions-financial.php">Financial</a>
          </li>
          <li><a href="solutions-homecare.php">Home Care</a>
          </li>
          <li><a href="solutions-itstaff.php">IT Staff</a>
          </li>
          <li><a href="solutions-surgical.php">Surgical</a>
          </li>
          <li><a href="solutions-ambulatory.php">Ambulatory</a>
          </li>
          <li>Oncology
          </li>
        </ul>
      </div>
      <div class="medium-4 column">
        <h4><a href="events.php">Events</a></h4>
        <ul>
          <li>HIMSS
          </li>
          <li>CIO Technology Forum
          </li>
          <li><a href="events-physician.php">Physician Forum</a>
          </li>
          <li>Nurse and Home Care Forum
          </li>
        </ul>
        <h4><a href="news.php">News</a></h4>
        <h4><a href="about.php">About</a></h4>
        <ul>
          <li>Careers
          </li>
          <li><a href="directions.php">Directions</a>
          </li>
          <li><a href="community.php">Community</a>
          </li>
          <li><a href="leadership.php">Leadership</a>
          </li>
          <li>International
          </li>
        </ul>
      </div>
      <div class="medium-4 column">
        <h4><a href="contact.php">Contact</a></h4>
        <h4>Shareholders Information</h4>
        <h4>Customer</h4>
        <h4>Follow Us</h4>
        <ul>
          <li><a href="https://www.facebook.com/MeditechEHR?ref=br_tf">Facebook</a>
          </li>
          <li><a href="https://twitter.com/MEDITECH">Twitter</a>
          </li>
          <li><a href="https://www.youtube.com/user/MEDITECHvideo">Youtube</a>
          </li>
          <li><a href="http://instagram.com/meditechehr/">Instagram</a>
          </li>
          <li><a href="http://www.pinterest.com/meditechehr">Pinterest</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
<!-- END SITEMAP -->


<!-- FOOTER FOOTER -->
  <div class="footerbottom">
    <div class="row">
      <div class="medium-6 column">
        <h5>Medical Information Technolgy, Inc.</h5>
      </div>
      <div class="medium-6 column">
        <ul style="list-style:none;">
          <li><a href="#">Privacy Policy</a>
          </li>
          <li><a href="#">Copyright Info</a>
          </li>
          <li><a href="#">Terms &amp; Conditions</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
<!-- END FOOTER FOOTER -->

</footer>


<!--</div>
 #page -->

<!--</div>
 .sb-site -->
<!-- These closing divs are for the slidebars navigation in the header include -->


<!-- LEFT SIDEBAR MENU
<div class="sb-slidebar sb-left">
  <nav>
    <ul class="sb-menu">-->
      <!-- SOLUTIONS
      <li><a href="solutions.php">EHR Solutions</a>
      </li>-->
      <!-- EVENTS
      <li><a href="events.php">Events</a>
      </li>-->
      <!-- NEWS
      <li><a href="news.php">News</a>
      </li>-->
      <!-- ABOUT
      <li><a href="about.php">About</a>
      </li>-->
      <!-- CONTACT
      <li><a href="contact.php">Contact</a>
      </li>
    </ul>
  </nav>
</div>-->
<!-- END LEFT SIDEBAR MENU -->


<!-- RIGHT SIDEBAR MENU -->
<!-- <div class="sb-slidebar sb-right">
    <h2>Please login to your MEDITECH account</h2>
    <nav>
      <ul class="sb-menu">
        <li>
          <input type="text" placeholder="Username">
        </li>
        <li>
          <input type="text" placeholder="Password">
        </li>
        <li>
          <input class="button expand" type="submit" id="searchsubmit" value="Login" />
        </li>
      </ul>
    </nav>
    <p>Trouble logging in?
      <br>Please visit <a href="#" style="color:#009abc;">our login page</a> for more detailed instructions.</p>
  </div> -->
<!-- End RIGHT SIDEBAR MENU -->




<!-- The if statement below loads an older version of jquery for IE users -->
<!--[if lt IE 9]>
    <script src="js/vendor/jquery-1.10.2.js"></script>
    <![endif]-->
<!-- The if statement below loads a newer version
        of JQuery that comes with Foundation 5 -->
<!--[if (gte IE 9) | (!IE)]><!-->
<script src="js/vendor/jquery.js"></script>
<!--<![endif]-->

<script src="js/foundation.min.js"></script>
<script type="text/javascript">
  $(document).foundation();
</script>
<!-- End of Foundation 5 files -->

<!-- Slidebars -->
<script src="js/menu/slidebars.min.js"></script>

<!-- Init scripts -->
<script type="text/javascript">
  // INITS & other scripts
  $(document).ready(function () {

    // Load Foundation
    $(document).foundation();

    // Load Sidebars
    var mySlidebars = new $.slidebars();

    // Closes Accordion
    $('.closeAccordion').click(function () {
      $('.accordion .content').removeClass('active');
    });
  });
</script>

<!-- Sticky Navigation - Function -->
<script src="js/stickynav/stickynav.js"></script>

<!-- Search Bar Dropdown Script -->
<!-- <script src="js/search/search.js"></script> -->

<!-- Polyfills fix for IE 8 & 9 -->
<script src="js/rem.min.js"></script>

</body>

</html>