<!doctype html>
<html class="no-js" lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>MEDITECH</title>
  <script src="js/vendor/modernizr.js"></script>

  <script src="//use.edgefonts.net/source-sans-pro.js"></script>

  <!-- Main Stylesheet -->
  <link type="text/css" rel="stylesheet" href="css/main.css">

  <!-- IE 8 & 9 Polyfills and other fixes
         - This is a combination of multiple IE specific .js files that
           help Foundation 5 work on IE 8 & 9. - JC -->
  <!--[if lt IE 9]>
    <script src="js/ie-js-files/ieFixes.min.js"></script>
  <![endif]-->

</head>

<body>
<!-- HEADER -->
  <header id="header">
    <div class="row">
      <!-- LOGO -->
      <div class="medium-6 columns">
        <h1 class="left logo"><a href="index.php">MEDITECH</a></h1>
      </div>
      <!-- SEARCH & LOGIN-->
      <div class="medium-6 columns">
        <div class="row topright">
          <!-- SEARCH -->
          <div class="medium-8 columns">
            <div class="row collapse">
              <div class="small-8 columns">
                <input type="text" placeholder="Search meditech.com">
              </div>
              <div class="small-4 columns">
                <a href="#" class="button postfix">Search</a>
              </div>
            </div>
          </div>
          <!-- LOGIN -->
          <div class="medium-4 columns">
            <a href="#" class="button tiny expand clogin">Customer Portal</a>
          </div>
        </div>
      </div>
      <!-- End SEACH & LOGIN -->
    </div>
  </header>
<!-- END HEADER -->

<!-- ============================

        STICKY HEADER

================================= -->

<!-- NAV -->
<nav id="nav">
  <div class="row">
  <div class="column">
  <ul class="menu small">
    <li><a class="sb-toggle-left" href="#">Menu</a>
    </li>
  </ul>
  
  <h1 class="small"><a href="index.php">MEDITECH</a></h1>
  
  <h1 class="large"><a href="index.php">M</a></h1>
  
  <ul class="menu large">
    <li><a href="solutions.php">EHR Solutions</a>
    </li>
    <li><a href="events.php">Events</a>
    </li>
    <li><a href="news.php">News</a>
    </li>
    <li><a href="about.php">About</a>
    </li>
    <li><a href="contact.php">Contact</a>
    </li>
  </ul>
  
  <!-- Secondary Nav -->
  <ul class="nav-buttons">
    <li>
      <a class="search-menu sb-close" href="#"></a>
    </li>
    <li>
      <a class="login-menu sb-toggle-right" href="#"></a>
    </li>
  </ul>
  
  <!-- SEARCH DROPDOWN -->
  <div id="js-searchbox">
    <form class="searchform" role="search" method="get" id="searchform" action="">
      <input id="s" type="text" placeholder="Search meditech.com">
      <a href="#" class="button postfix">Search</a>
    </form>
  </div>
  <div class="clear"></div>
  </div>
  </div>
</nav>
<!-- End of NAV -->

<!-- ============================

        BEGIN CONTENT

================================= -->

<section id="js-content" role="main">
  <div id="sb-site">
    <div id="page">
    <!-- END of HEADER INCLUDE file -->

